/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import koneksi.koneksi;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.ButtonGroup;
/**
 *
 * @author G_host
 */
public class Pelanggan extends javax.swing.JFrame {

    /**
     * Creates new form Pelanggan
     */
   public Pelanggan() {
    initComponents();

    ButtonGroup bg = new ButtonGroup();
    bg.add(rlaki);
    bg.add(rperempuan);

    loadData();
    setButtonState("awal");

    tblplgn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int row = tblplgn.getSelectedRow();
            txtid.setText(tblplgn.getValueAt(row, 0).toString());
            txtnm.setText(tblplgn.getValueAt(row, 1).toString());
            String jk = tblplgn.getValueAt(row, 2).toString();
            if (jk.equals("Laki-laki")) rlaki.setSelected(true);
            else rperempuan.setSelected(true);
            txttelp.setText(tblplgn.getValueAt(row, 3).toString());
            txtalm.setText(tblplgn.getValueAt(row, 4).toString());
            setButtonState("pilih");
        }
    });

    bsimpan.addActionListener(e -> simpanData());
    bubah.addActionListener(e -> ubahData());
    bhapus.addActionListener(e -> hapusData());
    bbatal.addActionListener(e -> { clearForm(); setButtonState("awal"); });
    bkeluar.addActionListener(e -> dispose());
    bcari.addActionListener(e -> cariData());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnm = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txttelp = new javax.swing.JTextField();
        rlaki = new javax.swing.JRadioButton();
        rperempuan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalm = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        bsimpan = new javax.swing.JButton();
        bubah = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblplgn = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA PELANGGAN");

        jLabel2.setText("ID Pelanggan");

        jLabel3.setText("Nama Pelanggan");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("No Telp.");

        jLabel6.setText("Alamat");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txttelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelpActionPerformed(evt);
            }
        });

        rlaki.setText("Laki-laki");
        rlaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlakiActionPerformed(evt);
            }
        });

        rperempuan.setText("Perempuan");

        txtalm.setColumns(20);
        txtalm.setRows(5);
        jScrollPane1.setViewportView(txtalm);

        bsimpan.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        bsimpan.setText("Simpan");

        bubah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        bubah.setText("Ubah");

        bhapus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        bhapus.setText("Hapus");

        bbatal.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        bbatal.setText("Batal");

        bkeluar.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        bkeluar.setText("Keluar");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Data Pelanggan");

        txtcari.setText("...");

        bcari.setText("Cari");

        tblplgn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama Pelanggan", "Jenis Kelamin", "No. Telp", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(tblplgn);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Copyright@ Ryan Ikramullah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addComponent(txtnm)
                                    .addComponent(txttelp, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rlaki)
                                        .addGap(18, 18, 18)
                                        .addComponent(rperempuan))
                                    .addComponent(jScrollPane1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bsimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bbatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bkeluar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rlaki)
                    .addComponent(rperempuan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(bubah)
                    .addComponent(bhapus)
                    .addComponent(bbatal)
                    .addComponent(bkeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txttelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelpActionPerformed

    private void rlakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rlakiActionPerformed
private Connection getConn() {
    return koneksi.connect();
}

private void loadData() {
    DefaultTableModel model = (DefaultTableModel) tblplgn.getModel();
    model.setRowCount(0);
    try (Connection con = getConn();
         Statement st = con.createStatement();
         ResultSet rs = st.executeQuery("SELECT * FROM pelanggan")) {
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id"),
                rs.getString("nmplg"),
                rs.getString("jenis"),
                rs.getString("telepon"),
                rs.getString("alamat")
            });
        }
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
    }
}

private void clearForm() {
    txtid.setText("");
    txtnm.setText("");
    txttelp.setText("");
    txtalm.setText("");
    rlaki.setSelected(false);
    rperempuan.setSelected(false);
}

private void setButtonState(String state) {
    switch (state) {
        case "awal":
            bsimpan.setEnabled(true);
            bubah.setEnabled(false);
            bhapus.setEnabled(false);
            bbatal.setEnabled(false);
            break;
        case "pilih":
            bsimpan.setEnabled(false);
            bubah.setEnabled(true);
            bhapus.setEnabled(true);
            bbatal.setEnabled(true);
            break;
    }
}

private void simpanData() {
    String id   = txtid.getText().trim();
    String nama = txtnm.getText().trim();
    String jk   = rlaki.isSelected() ? "Laki-laki" : rperempuan.isSelected() ? "Perempuan" : "";
    String telp = txttelp.getText().trim();
    String almt = txtalm.getText().trim();

    if (id.isEmpty() || nama.isEmpty() || jk.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "ID, Nama, dan Jenis Kelamin wajib diisi!");
        return;
    }
    try (Connection con = getConn();
         PreparedStatement ps = con.prepareStatement(
             "INSERT INTO pelanggan VALUES (?,?,?,?,?)")) {
        ps.setString(1, id);
        ps.setString(2, nama);
        ps.setString(3, jk);
        ps.setString(4, telp);
        ps.setString(5, almt);
        ps.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        loadData();
        clearForm();
        setButtonState("awal");
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
    }
}

private void ubahData() {
    String id   = txtid.getText().trim();
    String nama = txtnm.getText().trim();
    String jk   = rlaki.isSelected() ? "Laki-laki" : "Perempuan";
    String telp = txttelp.getText().trim();
    String almt = txtalm.getText().trim();

    try (Connection con = getConn();
         PreparedStatement ps = con.prepareStatement(
             "UPDATE pelanggan SET nama_pelanggan=?, jenis_kelamin=?, no_telp=?, alamat=? WHERE id_pelanggan=?")) {
        ps.setString(1, nama);
        ps.setString(2, jk);
        ps.setString(3, telp);
        ps.setString(4, almt);
        ps.setString(5, id);
        ps.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        loadData();
        clearForm();
        setButtonState("awal");
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal ubah: " + e.getMessage());
    }
}

private void hapusData() {
    if (javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?") != 0) return;
    String id = txtid.getText().trim();
    try (Connection con = getConn();
         PreparedStatement ps = con.prepareStatement(
             "DELETE FROM pelanggan WHERE id_pelanggan=?")) {
        ps.setString(1, id);
        ps.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        loadData();
        clearForm();
        setButtonState("awal");
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal hapus: " + e.getMessage());
    }
}

private void cariData() {
    String keyword = txtcari.getText().trim();
    DefaultTableModel model = (DefaultTableModel) tblplgn.getModel();
    model.setRowCount(0);
    try (Connection con = getConn();
         PreparedStatement ps = con.prepareStatement(
             "SELECT * FROM pelanggan WHERE id_pelanggan LIKE ? OR nama_pelanggan LIKE ?")) {
        ps.setString(1, "%" + keyword + "%");
        ps.setString(2, "%" + keyword + "%");
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_pelanggan"),
                rs.getString("nama_pelanggan"),
                rs.getString("jenis_kelamin"),
                rs.getString("no_telp"),
                rs.getString("alamat")
            });
        }
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal cari: " + e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rlaki;
    private javax.swing.JRadioButton rperempuan;
    private javax.swing.JTable tblplgn;
    private javax.swing.JTextArea txtalm;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txttelp;
    // End of variables declaration//GEN-END:variables
}
